// Copyright 2022 Blues Inc.  All rights reserved.
// Use of this source code is governed by licenses granted by the
// copyright holder including that found in the LICENSE file.

// Ingests data generated by a radar device
package main

import "fmt"

// Ingest a contact
func ingestContact(deviceUID string, deviceSN string, contactName string, contactAffiliation string, contactRole string, contactEmail string) (err error) {

	fmt.Printf("ingestContact: %s (%s) name:'%s' affiliation:'%s' role:'%s' email:'%s'\n", deviceUID, deviceSN, contactName, contactAffiliation, contactRole, contactEmail)

	return
}

// Ingest a scan entry
func ingestScan(deviceUID string, scan RadarScan) (err error) {

	fmt.Printf("ingestScan: %s %+v\n", deviceUID, scan)

	return
}

// Ingest a track entry
func ingestTrack(deviceUID string, scan RadarTrack) (err error) {

	fmt.Printf("ingestTrack: %s %+v\n", deviceUID, scan)

	return
}
